### DISCUSSION TITLE
Import CSS Modules styles into StyleX

### DISCUSSION THREAD

**Discussion by andrewright** [facebook/stylex#110] [General]
**Describe a solution you'd like:**
CSS Modules style sheet import into StyleX structure to modify and it on a fly and take instant result.
One of the coolest feature which provided StyleX is style compilation in JS, It is useful when calculation of our style runs in JS. We need it for in such cases as animation.

**Comment by necolas** [comment]
Please try explaining what you're asking for again, maybe with code examples? If you're asking for StyleX to consume CSS modules, that's not possible.

**Comment by nmn** [comment]
This feels like a discussion topic for now.

**Comment by andrewright** [comment]
I will try.
Let's take a project with CSS Modules used for style sheets. 
There are many calculations in Javascript code, which to be provided to the CSS.

Like a solution, import some of CSS Modules stylistic into StyleX calcluata it and apply to the element.

```css
//Button.module.css
.button {
  background-color: red;
  height: 20px;
}
```
```tsx
//MyComponent.tsx
import styles from './Button.module.css'
function MyComponent() {
  return <button className={styles.button}>My Button</button>;
}
```
```css
//Result
.button {
  background-color: red;
}
```
---
```css
//Button.module.css
.button {
  background-color: red;
}
```
```tsx
//MyComponent.tsx
import styles from './Button.module.css'
import * as stylex from '@stylexjs/stylex';

//just imagine the name of it: stylex.extend , stylex.import,...
const styles = stylex.extend(styles.button, {
  anotherButton: (height) => ({
    height,
  }),
});

function MyComponent() {
  // The value of `height` cannot be known at compile time.
  const [height, setHeight] = useState(100);

  return <button {...stylex.props(styles.anotherButton(height))}>Another button</button> ;
}
```
```css
//Result
.button {
  background-color: red;
  height: 100px;
}
```


The idea, to have opportunity, migrate of extend on party use StyleX powerful features.
