### DISCUSSION TITLE
How to use vendor prefixes

### DISCUSSION THREAD

**Discussion by olivierpascal** [facebook/stylex#362] [Q&A] [answered]
Hello, how can I use vendor prefixes, like:

```css
.clamp-lines {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
}
```
