### DISCUSSION TITLE
Strange output generated by stylex with webpack

### DISCUSSION THREAD

**Discussion by adrian-novacescu** [facebook/stylex#494] [Q&A] [answered]
Hi,

We started using stylex in our product and although it works great, the output of the css file looks strange.

```css
.xdpqu6t:not(#\#){padding:8px var(--xk99hms)}
.xe3t0ma:not(#\#){padding:var(--x1gsase5) var(--x1cp0i28)}
.x9r1u3d:not(#\#):not(#\#){border-color:transparent}
.x6vskdb:not(#\#):not(#\#){border-color:var(--x4b0og2)}
.xixl9f9:not(#\#):not(#\#){border-radius:14px}
.xgqmno8:not(#\#):not(#\#){border-radius:16px}
.x11j6hjo:not(#\#):not(#\#){border-radius:var(--x149zaps)}
.x1jrafhy:not(#\#):not(#\#){border-radius:var(--x16ufu40)}
.x1uioq7m:not(#\#):not(#\#){border-radius:var(--x17sycxl)}
.x15tiq8k:not(#\#):not(#\#){border-radius:var(--x1m44fmx)}
```

I am using stylex": "0.4.1" since the storybook crashes with latest webpack version and latest version of stylex does not work with previous webpack. 
However, I tried it with the latest version without storybook but the output looks the same. 
Except from the weird format, everything works as expected. My styles are applied but it is really hard to debug it and also the size of the css is about 50% bigger due to that invalid id selector in the not pseudo-class.

I did a small node script that removes that after build and it works ok. However, in dev mode I still have them like this for each style.

Looking forward to your answer,
Adi
