### DISCUSSION TITLE
Custom scrollbars

### DISCUSSION THREAD

**Discussion by OfirValla** [facebook/stylex#496] [General]
Hello, 
How can i create a stylex variable for the following css
```css
::-webkit-scrollbar {
    width: 20px;
}

::-webkit-scrollbar-thumb {
    background-color: #d6dee1;
    border-radius: 20px;
    border: 6px solid transparent;
    background-clip: content-box;
}

    ::-webkit-scrollbar-thumb:hover {
        background-color: #a8bbbf;
    }
```
