### DISCUSSION TITLE
Using stylex defined vars in global css

### DISCUSSION THREAD

**Discussion by meza** [facebook/stylex#562] [Q&A]
Hey,

I'm trying to wrap my head around stylex and the only outstanding question I have is around global css questions.

I have an app level setup for some of the basic styles for things like headings, body, main, article, img, etc...
I understand that these are supposed to stay as vanilla html for now, although I wish I could define these in StyelX too.

So the question is

How do I deal with something like this?

```css
form:invalid [type="submit"] {
  background-color: var(--colour-background-secondary);
  border: var(--border);
  box-shadow: none;
  color: var(--colour-text-secondary);
  cursor: not-allowed;
}
```

I would like to define my theme/variables purely in stylex so I could reuse them in all my components.
How can I make sure I can reuse them in the vanilla css parts too without having to duplicate them?
