### DISCUSSION TITLE
Question about 'styles at a distance' and prose

### DISCUSSION THREAD

**Discussion by zaydek** [facebook/stylex#812] [General]
Hi, I usually use StyleX for everything but I found there was this one specific case I couldn't seem to use StyleX so I reverted to plain CSS. Here is the code in question:

```css
[data-prose] {
  color: white;
  font-size: 15px;
  line-height: 1.5;
}
[data-prose] > *:first-child {
  margin-block-start: 0 !important;
}
[data-prose] :is(h1, h2, h3, h4, h5, h6) {
  font-weight: 700;
  line-height: 1.25;
  margin-block-start: 2rem;
  position: relative;
  scroll-margin-block-start: 2rem;
}
[data-prose] :is(h1, h2, h3, h4, h5, h6) a[href] {
  opacity: 0;
  color: blue;
  inset-block-start: 0;
  inset-inline-end: 100%;
  padding-inline-end: 0.5ch;
  position: absolute;
  text-decoration: none;
}
[data-prose] :is(h1, h2, h3, h4, h5, h6):hover a[href] {
  opacity: 1;
}

[data-prose] h1 {
  font-size: 1.5rem;
}
[data-prose] h2 {
  font-size: 1.375rem;
}
[data-prose] h3 {
  font-size: 1.25rem;
}
[data-prose] h4 {
  font-size: 1.125rem;
}
[data-prose] h5 {
  font-size: 1rem;
}
[data-prose] h6 {
  font-size: 0.875rem;
}
[data-prose] p {
  margin-block-start: 1rem;
}
[data-prose] ul {
  list-style-type: disc;
  padding-inline-start: 1rem;
}
[data-prose] ol {
  padding-inline-start: 1rem;
}
[data-prose] li {
  margin-block: 0.5em;
}
[data-prose] pre {
  background-color: color-mix(in hsl, transparent, white 10%);
  font-family: "Consolas", monospace;
  font-size: 0.875rem;
  margin-block: 1rem;
  padding: 16px;
}
[data-prose] code:not(pre code) {
  background-color: color-mix(in hsl, transparent, white 10%);
  border-radius: 4px;
  box-shadow: inset 0 0 0 1px color-mix(in hsl, transparent, white 25%);
  font-family: "Consolas", monospace;
  font-size: 0.875rem;
  padding: 4px;
}
```

Which is being used as a side effect by the following:

```tsx
<div data-prose>
  <ReactMarkdown
    components={{
      h1: ({ node, ...props }) => <AnyHeader {...props} node={node} type="h1" />,
      h2: ({ node, ...props }) => <AnyHeader {...props} node={node} type="h2" />,
      h3: ({ node, ...props }) => <AnyHeader {...props} node={node} type="h3" />,
      h4: ({ node, ...props }) => <AnyHeader {...props} node={node} type="h4" />,
      h5: ({ node, ...props }) => <AnyHeader {...props} node={node} type="h5" />,
      h6: ({ node, ...props }) => <AnyHeader {...props} node={node} type="h6" />,
    }}
  >
    {markdown}
  </ReactMarkdown>
</div>
```

What I don't understand is how to implement the following pattern using StyleX if possible:

```css
[data-prose] > *:first-child { ...
[data-prose] code:not(pre code) { ...
```

Because I am deferring to `<ReactMarkdown>`, it's not obvious to me how to programmatically disable the first `margin-block-start` or how to prevent `<code>` from being duplicately styled by the `<pre>` container.

Am I missing something or is this a legitimate use case for when not to reach for StyleX?
