### DISCUSSION TITLE
How to add at rules on top

### DISCUSSION THREAD

**Discussion by jonnitto** [facebook/stylex#860] [Q&A] [answered]
I want to add some at rules like this in the CSS file:

```css
@position-try --left {
  inset: auto;
  top: anchor(bottom);
  right: anchor(right);
}
```

How can I achieve this? I didn't found anything in the documentation, neither here or in the issues…
