### ISSUE TITLE
Support dark mode by class

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#122]
**Is your feature request related to a problem? Please describe.**

My app set dark mode with `<html data-mode="dark">`.
I don't think there is a way to use stylex to generate a css style like `:is([data-mode="dark"] .myclass) { ... }`.

**Describe a solution you'd like**
**Describe alternatives you've considered**
**Additional context**

**Comment by timwehrle** [comment]
You can have a look at the [Next.js example](https://github.com/facebook/stylex/blob/main/apps/nextjs-example/app/layout.tsx) to see how it might be done.

I don't know if this is your question or not, but try to be explicit about what you want support for.

**Comment by olivierpascal** [comment]
Of course: for the needs of my app, i need to be able to demo a component in both light and dark mode on the same screen.

```html
<div data-mode="light">
  <MyStyledComponent className="myComponent" />
</div>
<div data-mode="dark">
  <MyStyledComponent className="myComponent" />
</div>
```

I cannot use `@media (prefers-color-scheme: light/dark)` because this is OS specific (unaffected by th `color-scheme` css property).

I would like to be able to generate a style like:

```css
:root {
  --primary: red;
}

:is([data-mode="dark"]) {
  --primary: blue;
}

.myComponent {
  color: var(--primary);
}
```

Maybe from something like:

```js
// tokens.stylex.js

import * as stylex from '@stylexjs/stylex';

export const colors = stylex.defineVars({
  primary: {
    default: 'red',
    ':is[dark-mode="dark"]': 'blue',
  },
});
```

```js
// MyComponent.jsx

import { colors } from './tokens.stylex';

const styles = stylex.create({
  myComponent: {
    default: colors.primary,
  },
});

// ...
```

What do you think?

**Comment by olivierpascal** [comment]
Or, to generate a style like:

```css
:root {
  --primary: red;
  --primary-dark: blue;
}

.myComponent {
  color: var(--primary);
}

:is([data-mode="dark"]) .myComponent {
  color: var(--primary-dark);
}
```

Maybe from something like:

```js
// tokens.stylex.js

import * as stylex from '@stylexjs/stylex';

export const colors = stylex.defineVars({
  primary: 'red',
  'primary-dark': 'blue',
});
```

```js
// MyComponent.jsx

import { colors } from './tokens.stylex';

const styles = stylex.create({
  myComponent: {
    color: {
      default: colors.primary,
      ':is[dark-mode="dark"]': colors['primary-dark'],
    }
  },
});

// ...
```

**Comment by purohitdheeraj** [comment]
hey @olivierpascal 
how about using the required component as nested object
psuedoSelector(dark).myComponent : colorValue
psuedoSelector(light).myComponent : colorValue

for this there is a reference on docs, see if it helps
[defining styles](https://stylexjs.com/docs/learn/styling-ui/defining-styles/#combining-conditions)

correct me if it doesn't relate to your usecase

**Comment by olivierpascal** [comment]
Mmmh, the problem is that the pseudo selector ':is[dark-mode="dark"]' should be at the root level and hence placed before the class name. I don't think it's possible to do so with a nested object, at the component level.

**Comment by olivierpascal** [comment]
I think for my use case, the best API would be something like:

```js
// tokens.stylex.js

import * as stylex from '@stylexjs/stylex';

export const colors = stylex.defineVars({
  primary: {
    default: 'red',
    ':is[dark-mode="dark"]': 'blue',
  },
  secondary: {
    default: 'green',
    ':is[dark-mode="dark"]': 'black',
  },
});
```

-or-

```js
// tokens.stylex.js

import * as stylex from '@stylexjs/stylex';

export const colors = stylex.defineVars({
  default: {
    primary: 'red',
    secondary: 'green',
  },
  ':is[dark-mode="dark"]': {
    primary: 'blue',
    secondary: 'dark',
  },
});
```

**Comment by olivierpascal** [comment]
Sorry to spam. I just see that [stylexjs.com], which  is achieving just this:

```css
:root {
    --ifm-color-primary: #872291;
    /* ... */
}

html[data-theme=dark]:root {
    --ifm-color-primary: #be51c8;
    /* ... */
}
```

I guess it uses stylex. So the question is: how? 😲
