### ISSUE TITLE
Seeing a bunch of `:not(#\#)` when building css for the `apps/webpack-example`

### ISSUE THREAD

**Issue by tpavlu** [facebook/stylex#131]
**The problem**
I am evaluating this tool for usage and I noticed a bunch of erroneous css selectors that seemed odd.
This is the output css I am seeing when running basic example webpack implementation.
```css
@keyframes xgnty7z-B{0%{opacity:.25;}100%{opacity:1;}}
.x1oz5o6v:hover:not(#\#):not(#\#){background:red}
.xeuoslp:not(#\#):not(#\#):not(#\#){animation-name:xgnty7z-B}
.x1lliihq:not(#\#):not(#\#):not(#\#){display:block}
.x78zum5:not(#\#):not(#\#):not(#\#){display:flex}
.x1hm9lzh:not(#\#):not(#\#):not(#\#){margin-inline-start:10px}
.x1egiwwb:not(#\#):not(#\#):not(#\#):not(#\#){height:500px}
.xlrshdv:not(#\#):not(#\#):not(#\#):not(#\#){margin-top:99px}
.xh8yej3:not(#\#):not(#\#):not(#\#):not(#\#){width:100%}
.x3hqpx7:not(#\#):not(#\#):not(#\#):not(#\#){width:50%}%
```

**How to reproduce**
Steps to reproduce:
- Checkout the repo
- npm install in both root and in `apps/webpack-example`
- run `npm run build`
- run `cat .build/styles.css`

**Expected behavior**
I am not 100% sure the expected output here but I would assume it should have less if not none `:not` selectors and if there are `:not()` selectors they should have an actual id they are trying to select on.

**Environment (include versions). Did this work in previous versions?**
Not sure about previous versions but I am running on mac OSX and I just checked the repo out today this is my current SHA
`b32b183447c41e11672a200b3f04328cfc895935`

**Comment by tpavlu** [comment]
For additional context here I see that setting `useCSSLayers: true` in my webpack config results in `@layer` definitions instead of a bunch of `:not(#\#)` selectors but I am still a bit confused as to why this extra content is needed at all?

The [docs](https://stylexjs.com/docs/learn/thinking-in-stylex/#modularity-and-composability) say
```tsx
const styles = stylex.create({
  red: {color: 'red'},
});
```
Should convert to
```css
.x1e2nbdu {
  color: red;
}
```
But I am seeing 
```css
.x1e2nbdu:not(#\#){color:red}
```

Since one of the big benefits of this approach over something like postcss is the size of the output I would expect these redundant `:not()` selectors to be purged.
