### ISSUE TITLE
Better debug mode

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#184]
**Is your feature request related to a problem? Please describe.**

In debug mode, vars and classes should be more explicit.

**Describe a solution you'd like**

Instead of:

```css
:root {
    --x3dc7yf: #000;
    --x1f68uuh: #22005d;
    --xa37eq0: #381e72;
}

.x14cfrr {
    color: var(--x3dc7yf);
}
```

I would love to see:

```css
:root {
    --x3dc7yf-primary: #000;
    --x1f68uuh-secondary: #22005d;
    --xa37eq0-tiertiary: #381e72;
}

.x14cfrr-myButton {
    color: var(--x3dc7yf-primary);
}
```
