### ISSUE TITLE
[eslint-plugin] `transition` css property should be allowed

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#207]
**Is your feature request related to a problem? Please describe.**

The css property `transition` in `stylex.create()` is discouraged in profit of `transitionProperty`, `transitionDuration` and `transitionTimingFunction`, and eslint-plugin trigger a `This is not a key that is allowed by stylexeslint(@stylexjs/valid-styles)`. I got it.

But sometimes, `transition` has no alternative, for example if you want to animate multiple properties independantly:

```css
.transition {
  transition: opacity 150ms linear, background-color: 15ms linear;
}
```

**Describe a solution you'd like**

Allow `transition`.

**Describe alternatives you've considered**

```js
// eslint-disable-next-line @stylexjs/valid-styles
transition: 'opacity 150ms linear, background-color: 15ms linear',
```

**Comment by layershifter** [comment]
FYI, you can use commas in shorthand properties, too. I.e.

```css
.transition {
  transition: opacity 150ms linear, background-color 150ms linear;
}

/* ⬇️ */

.transition {
    transition-duration: 150ms, 150ms;
    transition-timing-function: linear, linear;
    transition-property: opacity, background-color;
}
```

<img width="310" alt="image" src="https://github.com/facebook/stylex/assets/14183168/1ea926ac-c8a5-450b-8f2e-b3644743b4b7">
