### ISSUE TITLE
animationName should also take multiple animations

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#213]
**Is your feature request related to a problem? Please describe.**

I want to output the following css:

```css
.container {
  animation-name: grow, shrink;
}
```

Note the two successive animations.

But in respect to https://stylexjs.com/docs/api/javascript/keyframes/, `animationName` can take only one animation.

**Describe a solution you'd like**

I suggest `animationName` could take an array of animations.
