### ISSUE TITLE
The CSS output contains many '#' characters

### ISSUE THREAD

**Issue by doiya46** [facebook/stylex#285]
Repo: https://github.com/doiya46/nx-stylex-demo
Node: > v18
Start: `yarn install && yarn serve:build`

```css
.x1awj2ng:not(#\#):not(#\#):not(#\#) {
    color: white;
}
<style>
.x1f2sqcu:not(#\#):not(#\#):not(#\#) {
    background-color: var(--x1p7recj);
}
```

This is example of css output file and the html didn't load to index.html.

```css
:root{--x1p7recj:#2563eb;--x1mdxlg2:#dc2626;--x1juqtqt:#9333ea}.x1f2sqcu:not(#\#){background-color:var(--x1p7recj)}.x1awj2ng:not(#\#){color:#fff}
```

<img width="1277" alt="Screenshot 2023-12-30 at 21 56 19" src="https://github.com/facebook/stylex/assets/61301244/60a1d730-36b8-47a5-940f-93caa149762c">
