### ISSUE TITLE
CSS expressions are modified and become invalid during compilation

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#351]
**The problem**

Some CSS values are modified during compilation.

**How to reproduce**

```ts
const styles = stylex.create({
  host: {
    margin: `max(0px, (48px - ${vars.iconSize}) / 2)`,
  },
});
```

is compiled to:

```css
.x1luk75g:not(#\#) {
  margin: max(0,(48px - var(--x16dnrjz))/2);
}
```

Which is incorrect, because 0 must have a unit in px for that expression to be valid.

**Expected behavior**

Compile exactly as asked:

```css
.x1luk75g:not(#\#) {
  margin: max(0px, (48px - var(--x16dnrjz)) / 2);
}
```

---

Also, with no var:

```ts
const styles = stylex.create({
  host: {
    margin: 'max(0px, 28px)',
  },
});

The `margin` css property is purely and simply missing in compiled css.
