### ISSUE TITLE
Generated CSS is always suffixed with `:not(#\#)`

### ISSUE THREAD

**Issue by vinceau** [facebook/stylex#370]
### Describe the issue

I'm migrating a project to use StyleX, and I'm defining styles as per usual like so:

```ts
const styles = stylex.create({
  container: {
    marginBottom: "20px",
  },
  dateInfo: {
    marginRight: "auto",
    marginLeft: "5px",
    opacity: 0.6,
    fontSize: "15px",
  },
  fixedCardHeight: {
    height: "200px",
  },
  markdownContainer: {
    color: "#ccc",
    maxWidth: "700px",
  },
});
```

However, when I inspect the generated CSS, every selector is appended with a trailing `:not(#\#)`.

```css
.x1qk1tsj:not(#\#) {
	color: #ccc
}

.x1jvydc1:not(#\#) {
	font-size: 15px
}

.x197sbye:not(#\#) {
	opacity: .6
}

.x1m3v4wt:not(#\#):not(#\#) {
	height: 200px
}

.xieb3on:not(#\#):not(#\#) {
	margin-bottom: 20px
}

.xd8780z:not(#\#):not(#\#) {
	margin-left: 5px
}

.xack27t:not(#\#):not(#\#) {
	margin-right: auto
}

.xrgej4m:not(#\#):not(#\#) {
	max-width: 700px
}
```

The more components that I migrate to use StyleX, the longer the `:not(#\#)` chain is for some selectors, with some selectors having 3 or 4. e.g.

```css
.x1n2onr6:not(#\#):not(#\#):not(#\#) {
	position: relative
}

.x1m3v4wt:not(#\#):not(#\#):not(#\#):not(#\#) {
	height: 200px
}
```

I initially thought it was some form of disambiguation, but surely the randomly generated CSS selectors should be sufficient for that.

### Expected behavior

I would assume the expected generated CSS to just be like:

```css
.xrgej4m {
	max-width: 700px
}

.x1cnzs8 {
	padding-top: 20px
}

.x1dmp6jm {
	width: 80px
}
```

### Steps to reproduce

I'm using the following packages:

```json
{
    "@stylexjs/webpack-plugin": "^0.4.1",
    "@stylexjs/stylex": "^0.4.1"
}
```

**but I was initially using `v0.3.0` which also had this issue.**

with the Webpack configuration:

```ts
    new StylexPlugin({
      dev: isDevelopment,
      unstable_moduleResolution: {
        type: "commonJS",
        rootDir: webpackPaths.rootPath,
      },
      appendTo: "style.css",
    }),
```

### Additional comments

Why does it do this and is it by design? It makes all the CSS selector names really long and also greatly increases the size of the resulting CSS file.

**Comment by vinceau** [comment]
Is that logic meant to create really long `:not(#\#)` chains like so?
```css
.x1m3v4wt:not(#\#):not(#\#):not(#\#):not(#\#) {
	height: 200px
}
```
