### ISSUE TITLE
styleX is not working in next.js

### ISSUE THREAD

**Issue by dngwoodo** [facebook/stylex#395]
### Describe the issue

styleX doesn't work under certain conditions.

### Expected behavior

```css
@layer reset {
  * {
    box-sizing: border-box;
    padding: 0;
    margin: 0;
  }
}
```

If you don't import global.css into layout.tsx in nextjs, the styles in styleX won't work. Is there a reason for this?

### Steps to reproduce

Here is an [example](https://github.com/facebook/stylex/tree/main/apps/nextjs-example) 

https://github.com/facebook/stylex/blob/8a1892b4cd6c3ad664d4520295420932fce728b1/apps/nextjs-example/app/layout.tsx#L10 If you comment out that line, all the css will not work.
