### ISSUE TITLE
[@stylexjs/esbuild-plugin] The esbuld-plugin does not embed variables in the TypeScript build.

### ISSUE THREAD

**Issue by ueokande** [facebook/stylex#454]
### Describe the issue

When I use variables with the `@stylexjs/esbuild-plugin`, the plugin does not embed variables defined by `stylex.defineVars()` into the generated CSS.  It works in the ESM build as expected, but it does not work well in the TypeScript build.  Here is an example:

Built from ESM
```css
:root{--xd1a5w:black;--x1h2un6e:white;}
@media (prefers-color-scheme: dark){:root{--xd1a5w:white;--x1h2un6e:black;}}
.xb26llm:not(#\#){background-color:var(--x1h2un6e)}
.x1bbqryo:not(#\#){color:var(--xd1a5w)}
```

Built from TypeScript
```css
.x1e8mcya{background-color:var(--x1w3s4ik)}
.x9fir3{color:var(--x5x584n)}
```

### Expected behavior

The `@stylexjs/esbuild-plugin` embed variabled defined by `stylex.defineVars()` in the TypeScript build.

### Steps to reproduce

I reproduce it by the following versions:
  - @stylexjs/esbuild-plugin: 0.5.1
  - @stylexjs/stylex: 0.5.1
  - esbuild: 0.20.0

1. Build typescripts by the following configuration

```javascript
// build.mjs
import esbuild from 'esbuild';
import stylexPlugin from '@stylexjs/esbuild-plugin';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

esbuild.build({
  entryPoints: [`src/index.ts`],
  outdir: `./build`,
  bundle: true,
  plugins: [
    stylexPlugin({
      dev: false,
      generatedCSSFileName: path.resolve(__dirname, `build/stylex.css`),
      stylexImports: ['@stylexjs/stylex'],
      unstable_moduleResolution: {
        type: 'commonJS',
        rootDir: __dirname,
      },
    }),
  ],
})
```

```typescript
// src/index.ts
import * as stylex from '@stylexjs/stylex';
import { colors } from './tokens.stylex';

const styles = stylex.create({
  container: {
    color: colors.foreground,
    backgroundColor: colors.background,
  },
});

window.dummy = stylex.props(styles.container);
```

```typescript
// src/tokens.stylex.ts
import * as stylex from '@stylexjs/stylex';

const DARK = '@media (prefers-color-scheme: dark)';

export const colors = stylex.defineVars({
  foreground: { default: 'black', [DARK]: 'white' },
  background: { default: 'white', [DARK]: 'black' },
});
```

2. Compile and  bundle TypeScript files by `node build.mjs`
3. Check a generated CSS in the `build` directory

The full example project is available here:

- https://stackblitz.com/edit/stylexjsesbuild-plugin
