### ISSUE TITLE
[Feature Request] Implement `postcss-sort-media-queries`-like auto media query sort

### ISSUE THREAD

**Issue by SukkaW** [facebook/stylex#455]
### Describe the feature request

This could be implemented as an option of `stylexBabelPlugin.processStylexRules`.

See also: https://www.npmjs.com/package/postcss-sort-media-queries

**Comment by nmn** [comment]
We won't be doing this, but a feature to automatically detect and resolve conflicts between media queries is planned. It should result in the same experience in practice.

**Comment by eslym** [comment]
when there is a lots of media query, the generated media query is not guaranteed to ordered correctly
```css
@media (max-width: 480px){.fontSize-x97d2zc.fontSize-x97d2zc{font-size:.75rem}}
@media (max-width: 480px){.fontSize-x16xvv2x.fontSize-x16xvv2x{font-size:1.25rem}}
@media (max-width: 640px){.fontSize-xzqihf2.fontSize-xzqihf2{font-size:1.25rem}}
@media (max-width: 640px){.fontSize-x1jr4dfw.fontSize-x1jr4dfw{font-size:1.5rem}}
@media (max-width: 768px){.fontSize-x118u78a.fontSize-x118u78a{font-size:1.5rem}}
@media (max-width: 480px){.fontSize-x1hz897e.fontSize-x1hz897e{font-size:1.5rem}}
@media (max-width: 640px){.fontSize-xm4yhdm.fontSize-xm4yhdm{font-size:1rem}}
@media (max-width: 480px){.fontSize-xz5lva1.fontSize-xz5lva1{font-size:1rem}}
@media (max-width: 768px){.fontSize-x1edd32e.fontSize-x1edd32e{font-size:2.5rem}}
@media (max-width: 640px){.fontSize-x123g9ce.fontSize-x123g9ce{font-size:2rem}}
@media (max-width: 768px){.fontSize-x13qyk8x.fontSize-x13qyk8x{font-size:4rem}}
```
![Image](https://github.com/user-attachments/assets/48bb1189-eb09-43f6-84f2-d7404ffa2508)
