### ISSUE TITLE
Polyfill CSS `light-dark()` function to simplify theming

### ISSUE THREAD

**Issue by necolas** [facebook/stylex#464]
### Describe the feature request

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark

We should look into how far we can polyfill this feature to help with simplifying how themes are defined without having to use media query wrappers in `defineVars` and `createTheme`

**Comment by necolas** [comment]
I think if there is a safe "native" way to do something that fits within the StyleX constraints, we should prefer to try and polyfill that instead of adding new functions.

The support for user-space functions would be cool for people who want custom abstractions, and could work as a stop-gap for native features we either a) haven't polyfilled yet, or b) don't want to polyfill until a spec has stabilized somewhat. I don't have a good sense of whether `light-dark()` is relatively stable (other than it being shipped in Firefox), but it certain feels more ergonomic than the MQs for the same purpose.

**Comment by nmn** [comment]
Polyfilling the CSS `light-dark()` should be trivial, will prioritize it.

**Comment by nmn** [comment]
# RFC - The approach for polyfilling `light-dark()` correctly

I spent some time discussing this with @nitishmehrotra870 and we found a flaw with how LightningCSS polyfills `light-dark()`.

Since the implementation would be a bit custom, I decided to share an RFC to explain the problems in the LightningCSS polyfill and how we plan to solve it.

## Issue with LightningCSS Polyfill

LightningCSS relies on a "space hack" which involves setting a CSS variable value to a space or `initial`. This make a variable behave like a toggle. Here's an example:

This:
```css
:root { color-scheme: light dark; }
.foo { color: light-dark(black, white); }
```

Would get transformed into this:

```css
:root { --light-mode: initial; --dark-mode: ; }
@media (prefers-color-scheme: dark) {
  :root { --light-mode: ; --dark-mode: initial; }  
}
.foo { color: var(--light-mode, black) var(--dark-mode, white); }
```

Whichever variable is set to `initial` will cause the associated fallback value to be applied.
The variables set to ` ;` are considered to be "defined", but they only add whitespace to final value of color.

This polyfill is already good enough when `light-dark` is used for CSS properties. However, when `light-dark()` is used to set the value of a CSS variable, this approach doesn't work as expected.

Consider if the original code looked like this:

```css
:root { --light-mode: initial; --dark-mode: ; }
@media (prefers-color-scheme: dark) {
  :root { --light-mode: ; --dark-mode: initial; }  
}
.foo { --color: var(--light-mode, black) var(--dark-mode, white); }
.bar { color: var(--color); }
```

Consider the following transformed code:

```css
:root { --light-mode: initial; --dark-mode: ; }
@media (prefers-color-scheme: dark) {
  :root { --light-mode: ; --dark-mode: initial; }  
}
.foo { --color: var(--light-mode, black) var(--dark-mode, white); }
.bar { color: var(--color); }
```

Here, the class `bar` picks the final color based on the color-scheme that was active for `foo`, not for `bar`. This is *not* how `light-dark` is supposed to work.

## Proposed solution

The proposed solution is to detect every CSS variable that is *ever* set to a `light-dark` value and split it into two separate variables for `light` and `dark` respectively. And further, move the "space-hack" to where the variable is used instead.

Therefore the example above would be transformed to the following:

```css
:root { --light-mode: initial; --dark-mode: ; }
@media (prefers-color-scheme: dark) {
  :root { --light-mode: ; --dark-mode: initial; }  
}
.foo { --color_light: black; --color_dark: white; }
.bar { color: var(--light-mode, var(--color_light)) var(--dark-mode, var(--color_dark)); }
```

This ensures that the `light-dark` function isn't resolved too early.

### One Additional detail

In order to cover all edge-cases, it is also important to split variables that get a `light-dark()` function value indirectly.

e.g. if `--color: light-dark()` is used, and `--other-var: var(--color)` is used in the original CSS, then *both* `--color` *and* `--other-var` need to be split into `_light` and `_dark` variants. Therefore, detecting variables that can be set to `light-dark` will need to be done in a loop, over and over again, until there are no additional variables found.

### Caveat

We will not be able to polyfill usages of `light-dark()` within dynamic styles as they're not known ahead of time.

## Final Usage

Although there are a bunch of details to consider while implementing a polyfill for `light-dark`, the usage should be very simple.

1. You will be able to use `light-dark(val1, val2)` just like any other value.
2. It can be used within `stylex.create` styles and within theming APIs
3. There will be no need to use `@media (prefers-color-scheme: dark)` anymore
4. There will be no need to define separate "light", "dark" and "auto" themes
   1. Instead, you'd be able to define a single theme where the values are defined using `light-dark`
   2. You'd be able to set:
      - `color-scheme: light` for light mode
      - `color-scheme: dark` for dark mode
      - `color-scheme: light dark` for system
   3. `color-scheme` can be set on any element anywhere, and you can use it to mix and max light and dark mode within the same HTML page.
