### ISSUE TITLE
Rust Regex experts: Codeblocks and inline code in regex

### ISSUE THREAD

**Issue by kevintyj** [facebook/stylex#88]
### Problem
Hello StyleX community I'm working on a PR #87 for adding reserved words (with correct capitalization) for the spellchecker [typos](https://github.com/crate-ci/typos/blob/master/README.md) that the StyleX team uses to eliminate unnecessary PRs. 
I have forgotten that there are code blocks in markdown files that we would most likely want to ignore. The issue is the way that we can ignore such patterns is through regex and it does not support `backreferences` and `lookaround` [Rust Regex](https://docs.rs/regex/latest/regex/index.html#syntax). 
I have gotten this far:
```toml
extend-ignore-re = [
    "(`{3,}|~{3,})(\\w+)?\\s*", # Pattern for code blocks
    "([\\s\\S]*?)",
    "`[^`]+`", # Pattern for inline code snippets
]
```
This regex pattern detects all code blocks with either ~~~ or ```, but it seems to only capture the first instance of inline code snippets. Wanted to see if there was anyone with experience to help make this PR into a reality.

### Steps to reproduce
Clone the PR, install typos (using link above) run `typos` in root directory. Additional rules are as follows:
```toml
[type.md]
extend-glob = ["*.md", ".mdx"]
extend-ignore-re = [
    "(`{3,}|~{3,})(\\w+)?\\s*", # Pattern for code blocks
    "([\\s\\S]*?)",
    "`[^`]+`", # Pattern for inline code snippets
]
[type.md.extend-words]
stylex = "StyleX"
typescript = "TypeScript
```
